### ISSUE TITLE
Header file conflict with BQ24195 library

### ISSUE THREAD

**Issue by aliphys** [arduino-libraries/Arduino_PF1550#3]
In the example [BasicUsage.ino](https://github.com/arduino-libraries/Arduino_PF1550/blob/master/examples/BasicUsage/BasicUsage.ino), we call the `Arduino_PMIC.h` header file. 
https://github.com/arduino-libraries/Arduino_PF1550/blob/2852629d62e5f531142c81ab9297f9ae62423e63/examples/BasicUsage/BasicUsage.ino#L1

---

This is problematic for two main reasons:

- Firstly, the naming implies that there is a single unified interface for dealing with PMIC across the Arduino ecosystem. Which there isn't: we have four in active use AFAIK. This leads to confusion from a documentation point of view.
    - [BQ24195](https://github.com/arduino-libraries/Arduino_BQ24195) (used in MKR board)
    - [PF1550](https://github.com/arduino-libraries/Arduino_PF1550) (this one)
    - BD71847 (for the X8), and
    - [BQ25120](https://github.com/arduino/ArduinoCore-mbed/tree/master/libraries/Nicla_System/src)
- Secondly, given the way files are arranged library conflicts may occur between the [BQ24195](https://github.com/arduino-libraries/Arduino_BQ24195) and [PF1550](https://github.com/arduino-libraries/Arduino_PF1550) library since both have a `Arduino_PMIC.h` file. Depending upon which library is loaded first, it can block the other library from loading.
    - https://github.com/arduino-libraries/Arduino_PF1550/blob/2852629d62e5f531142c81ab9297f9ae62423e63/src/Arduino_PMIC.h#L19

---

**Possible Solutions**
-  **Quick fix:** In our examples, we directly call the relevant library. So instead of `Arduino_PMIC.h` we would use `BQ24195.h` or `PF1550.h`. This should be possible. Users are then advised to check which board they have and select the PMIC library accordingly. This would slightly reduce the portability of the code, but ensure that it runs correctly
- **Intensive Fix:** Have a wrapper library, which contains `Arduino_PMIC.h` that calls the relevant PMIC library based on the board selected in the IDE or (optionally) an option in the sketch directly. I assume this would require more work (and potentially break things). Yet it would make the user experience more fluid.
- **The third option** would be to integrate the PMIC library directly into the core variant. @giulcioffi and @facchinm have done this for the https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/Nicla_System/src/BQ25120A.h

---

Until a solution is decided upon & delivered, is it safe to use `PF1550.h` inside newly developed tutorials & app notes?
---
Related to:  https://github.com/arduino-libraries/Arduino_BQ24195/issues/23

**Comment by aliphys** [comment]
The [linter](https://github.com/arduino-libraries/Arduino_PF1550/actions/runs/3045245508/jobs/4906567126#step:3:17) shows an error which seems to be related to the header naming issue:
```
WARNING: No header file found matching library name (Arduino_PF1550.h). Best practices are for primary header filename  
         to match library name.                                                                                         
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
         (Rule LS008)      
```

**Comment by sebromero** [comment]
@aliphys When #20 gets merged, sketches should use the new `Arduino_PF1550.h` include instead. I already adjusted it in the example sketches.
